### PR TITLE
New test format

### PR DESCRIPTION
**Pull request by ashblue**
The PR is a large overhaul of the current testing format. Which is an attempt to make the coding test more approachable to candidates and avoid coding complex systems such as a form.

### CODE REVIEW

**Comment by jeffbergman** [comment]
Looks good, Ash. I have 2 thoughts.

1. Why do they need to email BuildIt with a link to their public version controlled files?
2. I'm a little confused about the following points, not quite sure what you intend them to do:

- Print an OMDb search query as a list of movies on a single page (example https://www.omdbapi.com/?s=star_wars&apikey=YOUR_KEY)
- Make a list of 3 different movie search queries on the same page

Do we want them to first print out the results of 1 query, and then extend it to 3 queries? Or something else?
If it's not clear to me, it might not be clear to the candidate.

**Comment by ashblue** [comment]
> Looks good, Ash. I have 2 thoughts.
> 
> 1. Why do they need to email BuildIt with a link to their public version controlled files?
> 2. I'm a little confused about the following points, not quite sure what you intend them to do:
> 
> * Print an OMDb search query as a list of movies on a single page (example https://www.omdbapi.com/?s=star_wars&apikey=YOUR_KEY)
> * Make a list of 3 different movie search queries on the same page
> 
> Do we want them to first print out the results of 1 query, and then extend it to 3 queries? Or something else?
> If it's not clear to me, it might not be clear to the candidate.

@jeffbergman Idea would be to have them print a hard coded query that the page loads with by default. Then extend that to allow swapping the printed result with the 3 queries. Is there a better way to word that?

**Comment by jeffbergman** [comment]
Do you mean that they're appending the results of each query to the previous one and displaying them all? That's what I don't understand.

**Comment by ashblue** [comment]
@jeffbergman It's a single page app so the results should get replaced each time a new query is made.

**Comment by ashblue** [comment]
I thought the item immediately after the two points you copy pasted helped make this clear, but maybe it needs to be reworded?

"1. Clicking a search query replaces printed movies with the query's results"

**Comment by joemacstevens** [comment]
I like the direction but I think the steps in the exercise are a little confusing. 

I think we should give them three specific query's to make and tell them to add three buttons. When the user clicks the button the results load below. Kind of like tabs

**Comment by joemacstevens** [comment]
I think the testing section is really good in that it tells them exactly what to test. The less the dev has to think about the better

**Comment by ashblue** [comment]
@joemacstevens Can you write a rough draft of what you think that might look like for the revised steps?

**Pull request merged**
